modification workflow api_deployment

diff --git a/.github/workflows/api_deployment.yaml b/.github/workflows/api_deployment.yaml
--- a/.github/workflows/api_deployment.yaml
+++ b/.github/workflows/api_deployment.yaml
@@ -30,22 +30,27 @@ jobs:
         
     - name: Create Azure Container Instance
       uses: azure/CLI@v2
-      with:
+       with:
         azcliversion: 2.61.0
         inlineScript: |
+          set -e  # Exit immediately if a command exits with a non-zero status
+          echo "Setting Azure subscription..."
           az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
           
-          # Check if the container exists
+          echo "Checking if the container instance exists..."
           container_exists=$(az container show --resource-group ${{ secrets.RESSOURCE_GROUP }} --name ${{ inputs.app_name }} --query "name" -o tsv || echo "notfound")
+          echo "Container exists status: $container_exists"
     
           if [ "$container_exists" != "notfound" ]; then
             echo "Container instance exists. Deleting..."
-            az container delete --resource-group ${{ secrets.RESSOURCE_GROUP }} --name ${{ inputs.app_name }} --yes
+            az container delete --resource-group ${{ secrets.RESSOURCE_GROUP }} --name ${{ inputs.app_name }} --yes --no-wait
+            az container wait --resource-group ${{ secrets.RESSOURCE_GROUP }} --name ${{ inputs.app_name }} --deleted
             echo "Container instance deleted."
           else
             echo "Container instance does not exist."
           fi
     
+          echo "Creating new container instance..."
           az container create \
             --resource-group ${{ secrets.RESSOURCE_GROUP }} \
             --name ${{ inputs.app_name }} \
@@ -65,8 +70,17 @@ jobs:
             "AZUREUSER"=${{ secrets.AZUREUSER }} \
             "PASSWORD"=${{ secrets.PASSWORD }} \
             "SECRET_KEY"=${{ secrets.SECRET_KEY }} \
-            "ENV"=${{ secrets.ENV }} 
+            "ENV"=${{ secrets.ENV }}
           echo "Container instance created."
 
     - name: Test Endpoint
-      run: curl -I ${{ inputs.app_name }}.francecentral.azurecontainer.io:8000/docs
+      run: |
+        echo "Testing endpoint..."
+        response=$(curl -I ${{ inputs.app_name }}.francecentral.azurecontainer.io:8000/docs)
+        echo "Endpoint response: $response"
+        if echo "$response" | grep "200 OK"; then
+          echo "Endpoint is working."
+        else
+          echo "Endpoint test failed."
+          exit 1
+        fi
